# Generated by Django 4.1.3 on 2022-12-14 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_blog_date_created_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date_created',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
