# Generated by Django 4.1.3 on 2022-12-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_blog_date_created_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
